### PR TITLE
Add VeraCrypt support

### PR DESCRIPTION
**Pull request by idrassi**
These patches implement support for VeraCrypt (https://veracrypt.codeplex.com), a fork of TrueCrypt.
The first two patches are not related to VeraCrypt but are needed by the third patch which implement VeraCrypt support.

The first patch corrects the encoding of the minimum version field in the volume header.
The second patch brings a better handling of PRF algorithms by separating those used in system encryption from those used in standard containers encryption.
The third patch adds a switch ("veracrypt-mode") to tc-play that will activated VeraCrypt support in the used commands. The differences between normal mode and VeraCrypt mode are:
- PRF algorithms Iterations count (much higher than in TrueCrypt)
- SHA256 support for system encryption and in standard containers.
- value minimum version field in the volume header is 0x010b instead of 0x0700.
- Volume header signature is "VERA" instead of "TRUE"

VeraCrypt documentation that is derived from TrueCrypt one (without the mistakes): https://veracrypt.codeplex.com/documentation

Differences between VeraCrypt and TrueCrypt : https://veracrypt.codeplex.com/discussions/569777#PostContent_1313325

### CODE REVIEW

**Comment by fcore117** [comment]
any progress on merge?

**Comment by xavier83** [comment]
looks like tc-play is dead.

**Comment by mhogomchungu** [comment]
Upstream seems to no longer care about it but it lives on with zuluCrypt[1] where all these patches are already in.

tc-play in zuluCrypt for example can create and unlock VeraCrypt volumes that use a PIM value.This ability is not among patches above.

[1] https://github.com/mhogomchungu/zuluCrypt/tree/master/external_libraries/tc-play

**Comment by kevinoid** [comment]
As someone currently evaluating cross-platform disk encryption options, I'd really like to see VeraCrypt support in tcplay.  Not least because the [TrueCrypt Security Assessment](https://opencryptoaudit.org/reports/iSec_Final_Open_Crypto_Audit_Project_TrueCrypt_Security_Assessment.pdf) specifically calls out the weak volume header key derivation "iteration count is too small to prevent password guessing attacks for even moderately complex passwords" which is addressed by VeraCrypt.

Perhaps now that a few more years have passed, the other TrueCrypt forks are dead or [stagnant](https://github.com/CipherShed/CipherShed/issues/49), [VeraCrypt has undergone its own security audit](https://ostif.org/the-veracrypt-audit-results/),  and [VeraCrypt support has been added to cryptsetup](https://gitlab.com/cryptsetup/cryptsetup/issues/245) and other similar tools, it's worth re-evaluating the merits of including support for VeraCrypt?

If this PR in its current form is not acceptable, is there any form which would be accepted?

**Comment by bwalex** [comment]
VeraCrypt support is now merged as a simple selection of PBKDF2 PRFs, without the need of any additional flags or API changes.

**Pull request closed without merging**
